/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        'brand-blue':  '#2563EB',
        'brand-dark':  '#0B192C',
        'bg-base':     'var(--bg-base)',
        'bg-card':     'var(--bg-card)',
        'white-pure':  '#ffffff',
        
        // Material 3 Fintech Surface & Color tokens
        'surface-container-low': '#f2f3ff',
        'surface-container-lowest': '#ffffff',
        'surface-container': '#eaedff',
        'surface-container-high': '#e2e7ff',
        'surface-container-highest': '#dae2fd',
        'on-surface': '#131b2e',
        'on-surface-variant': '#44474d',
        'outline-variant': '#c4c6ce',
        'outline': '#74777e',
        'secondary': '#0045de',
        'secondary-container': '#2c60ff',
        'on-secondary': '#ffffff',
        'secondary-fixed': '#dde1ff',
        'on-secondary-fixed-variant': '#0038b7',
        'on-tertiary-container': '#009d6d',
        'primary-container': '#0c2340',
        'on-primary-container': '#778bad',
        'primary': '#000d21',
        'on-primary': '#ffffff',
        'primary-fixed': '#d5e3ff',
        'primary-fixed-dim': '#b3c7ec',
        'secondary-hover': '#0038b7',
        'tertiary-fixed': '#6ffbbe',
        'on-tertiary-fixed-variant': '#005236',
        'surface': '#faf8ff',
        'surface-dim': '#d2d9f4',
        'error': '#ba1a1a',
        
        // Dark theme redirects for standard Tailwind utility classes
        white: 'var(--bg-card)',
        slate: {
          50: 'var(--bg-base)',
          100: 'var(--border-subtle)',
          200: 'var(--border-subtle)',
          250: 'var(--border-subtle)',
          300: '#1D2D44',
          350: '#1D2D44',
          400: 'var(--text-muted)',
          450: 'var(--text-muted)',
          500: 'var(--text-secondary)',
          550: 'var(--text-secondary)',
          600: 'var(--text-secondary)',
          650: 'var(--text-secondary)',
          700: 'var(--text-primary)',
          800: 'var(--text-primary)',
          850: 'var(--text-primary)',
          900: 'var(--text-primary)',
          950: '#020617',
        },
        blue: {
          50: 'rgba(51, 149, 255, 0.08)',
          100: 'rgba(51, 149, 255, 0.15)',
          200: 'rgba(51, 149, 255, 0.25)',
          500: 'var(--accent)',
          600: 'var(--accent)',
          650: 'var(--accent)',
          655: 'var(--accent)',
          700: 'var(--accent-light)',
          800: 'var(--accent-light)',
        }
      },
      fontSize: {
        'title-md': ['16px', { lineHeight: '24px', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'headline-sm': ['18px', { lineHeight: '26px', letterSpacing: '-0.005em', fontWeight: '600' }],
        'label-sm': ['10px', { lineHeight: '14px', letterSpacing: '0.02em', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.01em', fontWeight: '500' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.005em', fontWeight: '500' }],
        'currency-display': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
      fontFamily: {
        sans: ['var(--font-inter)', 'Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      borderRadius: {
        '2xl': '16px',
        '3xl': '28px',
        '4xl': '36px',
      },
      backdropBlur: {
        '2xl': '24px',
        '3xl': '40px',
      },
      animation: {
        'fade-up':      'fadeUp 0.5s cubic-bezier(0.22,1,0.36,1) forwards',
        'fade-in':      'fadeIn 0.4s ease forwards',
        'scale-up':     'scaleUp 0.4s cubic-bezier(0.34,1.56,0.64,1) forwards',
        'slide-right':  'slideRight 0.4s cubic-bezier(0.22,1,0.36,1) forwards',
        'float':        'float 3s ease-in-out infinite',
        'pulse-ring':   'pulseRing 2s cubic-bezier(0.455,0.03,0.515,0.955) infinite',
        'shake':        'shake 0.4s ease',
        'gradient':     'gradientShift 4s linear infinite',
        'progress':     'progress 20s linear infinite',
      },
      keyframes: {
        fadeUp:        { from: { opacity: '0', transform: 'translateY(24px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        fadeIn:        { from: { opacity: '0' }, to: { opacity: '1' } },
        scaleUp:       { from: { opacity: '0', transform: 'scale(0.85)' }, to: { opacity: '1', transform: 'scale(1)' } },
        slideRight:    { from: { opacity: '0', transform: 'translateX(-20px)' }, to: { opacity: '1', transform: 'translateX(0)' } },
        float:         { '0%,100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-8px)' } },
        pulseRing:     { '0%': { boxShadow: '0 0 0 0 rgba(0,186,242,0.5)' }, '70%': { boxShadow: '0 0 0 14px rgba(0,186,242,0)' }, '100%': { boxShadow: '0 0 0 0 rgba(0,186,242,0)' } },
        shake:         { '0%,100%': { transform: 'translateX(0)' }, '20%': { transform: 'translateX(-6px)' }, '40%': { transform: 'translateX(6px)' }, '60%': { transform: 'translateX(-4px)' }, '80%': { transform: 'translateX(4px)' } },
        gradientShift: { '0%': { backgroundPosition: '0% 50%' }, '50%': { backgroundPosition: '100% 50%' }, '100%': { backgroundPosition: '0% 50%' } },
        progress:      { from: { width: '0%' }, to: { width: '100%' } },
      },
    },
  },
  plugins: [],
};
